apiVersion: ex.operator/v1
kind: ExecutionPlan
metadata:
  name: example-executionplan
  namespace: andrew-space
spec:
  plans:
    - planName: test-plan
      deploymentNames:
        - nginx-deployment
      resources:
        - service
        - resource-2
status:
  error: false
  reason: "No issues. Creation"
  deploymentReplicaCounts:
  observedGeneration: 1
