apiVersion: v1
kind: ServiceAccount
metadata:
  name: execution-plan-operator
  namespace: andrew-space

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-plan-operator
  namespace: andrew-space
spec:
  selector:
    matchLabels:
      app: execution-plan-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: execution-plan-operator
    spec:
      serviceAccountName: execution-plan-operator
      containers:
        - name: operator
          image: kube-operator:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /startup
              port: 8080
            initialDelaySeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: execution-plan-operator
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "apps"
    resources:
      - deployments
      - services
      - pods
      - pods/exec
    verbs:
      - '*'
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "ex.operator"
    resources:
      - executionplans
      - executionplans/status
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: execution-plan-operator-admin
subjects:
  - kind: ServiceAccount
    name: execution-plan-operator
    namespace: andrew-space
roleRef:
  kind: ClusterRole
  name: execution-plan-operator
  apiGroup: ""